version: '3.5'

services:
  redis:
    image: redis
  db: 
    image: postgres
    environment:
      - POSTGRES_PASSWORD=example
  backend:
    image: docker-hy/backend
    ports:
      - 8000:8000
    environment:
      - REDIS=redis
      - DB_HOST=db
      - DB_USERNAME=postgres
      - DB_PASSWORD=example
  frontend:
    image: docker-hy/frontend
    ports: 
      - 5000:5000

