version: '3.5'

services:
  frontend:
    build: https://github.com/docker-hy/ml-kurkkumopo-frontend.git
    ports:
      - 3000:3000
  training:
    build: https://github.com/docker-hy/ml-kurkkumopo-training.git
    volumes:
      - imgs:/src/imgs
      - model:/src/model
      - data:/src/data
  backend:
    build: https://github.com/docker-hy/ml-kurkkumopo-backend.git
    volumes:
      - model:/src/model
    ports:
      - 5000:5000
volumes:
  imgs:
  model:
  data:
