version: '3.5'

services:
  redis:
    image: redis
  backend:
    image: docker-hy/backend
    ports:
      - 8000:8000
    environment:
      - REDIS=redis
  frontend:
    image: docker-hy/frontend
    ports:
      - 5000:5000
